const demoLiveBlueprint = {
  id: "pmslink-demo-blueprint",
  sourceInspectionId: 1,
  sourceLabel: "PMSLink demo capture",
  summary: {
    tested: 0,
    inspected: 12,
    notSighted: 0,
    notApplicable: 0,
    totalFindings: 3,
    questionCount: 12,
    evidenceCount: 6,
    ratingBand: "Medium",
    conditionScore: 3.8,
  },
  sections: [
    {
      id: "demo-section-hull",
      title: "Hull",
      comments: "Hull walkthrough completed during the seeded PMSLink demo inspection.",
      summary: {
        answered: 3,
        tested: 0,
        inspected: 3,
        notSighted: 0,
        notApplicable: 0,
        totalFindings: 1,
        evidenceCount: 2,
        questionCount: 3,
      },
      condition: { score: 4.0, scoredResponses: 3 },
      rating: { band: "High", mandatoryQuestions: 2, mandatoryQuestionsWithFindings: 0 },
      subsections: [
        {
          id: "demo-subsection-hull-1",
          title: "Cosmetic and Structural",
          location: "External Hull",
          checklistId: 1,
          areaId: 101,
          totalCount: 3,
          doneCount: 3,
          summary: {
            answered: 3,
            tested: 0,
            inspected: 3,
            notSighted: 0,
            notApplicable: 0,
            totalFindings: 1,
            evidenceCount: 2,
            questionCount: 3,
          },
          condition: { score: 4.0, scoredResponses: 3 },
          rating: { band: "High", mandatoryQuestions: 2, mandatoryQuestionsWithFindings: 0 },
          comments: "Coating, shell condition, and deck-edge appearance were verified.",
          questions: [
            {
              id: "demo-hull-q1",
              code: "H1",
              prompt: "Condition of shell plating and hull coating along exposed areas.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "General coating condition was satisfactory with only routine touch-up noted.",
              guidanceNotes: "Confirm the hull shell, boot-top, and visible coating remain fit for service.",
              areaOfConcern: "Hull",
              subAreaOfConcern: "Cosmetic and Structural",
              typeOfFinding: "",
              severity: "",
              files: [
                {
                  id: "demo-file-hull-1",
                  url: "/reference-images/deck-reference.svg",
                  caption: "Hull coating reference",
                  label: "Reference image",
                },
              ],
            },
            {
              id: "demo-hull-q2",
              code: "H2",
              prompt: "Any visible deformation, wastage, or shell damage requiring office follow-up?",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 3,
              finding: true,
              comments: "Minor paint breakdown noted at the forecastle edge. Monitor during next port stay.",
              guidanceNotes: "Highlight any local damage, corrosion progression, or deformation requiring planning attention.",
              areaOfConcern: "Hull",
              subAreaOfConcern: "Cosmetic and Structural",
              typeOfFinding: "Observation",
              severity: "LOW",
              files: [
                {
                  id: "demo-file-hull-2",
                  url: "/reference-images/deck-reference.svg",
                  caption: "Touch-up area reference",
                  label: "Finding image",
                },
              ],
            },
            {
              id: "demo-hull-q3",
              code: "H3",
              prompt: "Condition of vessel markings, draft marks, and over-side presentation.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 5,
              finding: false,
              comments: "Markings were clear and legible for the inspection scope.",
              guidanceNotes: "Confirm markings remain readable and in line with operating standards.",
              areaOfConcern: "Hull",
              subAreaOfConcern: "Cosmetic and Structural",
              typeOfFinding: "",
              severity: "",
              files: [],
            },
          ],
        },
      ],
    },
    {
      id: "demo-section-navigation",
      title: "Navigation",
      comments: "Bridge readiness and navigational assurance were reviewed using PMSLink demo records.",
      summary: {
        answered: 3,
        tested: 0,
        inspected: 3,
        notSighted: 0,
        notApplicable: 0,
        totalFindings: 1,
        evidenceCount: 2,
        questionCount: 3,
      },
      condition: { score: 3.7, scoredResponses: 3 },
      rating: { band: "Medium", mandatoryQuestions: 2, mandatoryQuestionsWithFindings: 1 },
      subsections: [
        {
          id: "demo-subsection-navigation-1",
          title: "Bridge Systems",
          location: "Bridge",
          checklistId: 2,
          areaId: 201,
          totalCount: 3,
          doneCount: 3,
          summary: {
            answered: 3,
            tested: 0,
            inspected: 3,
            notSighted: 0,
            notApplicable: 0,
            totalFindings: 1,
            evidenceCount: 2,
            questionCount: 3,
          },
          condition: { score: 3.7, scoredResponses: 3 },
          rating: { band: "Medium", mandatoryQuestions: 2, mandatoryQuestionsWithFindings: 1 },
          comments: "Navigation equipment, publications, and watchkeeping controls were sampled.",
          questions: [
            {
              id: "demo-nav-q1",
              code: "N1",
              prompt: "Berth-to-berth passage plan, watch orders, and bridge familiarization are current.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "Bridge planning documents were current and countersigned.",
              guidanceNotes: "Confirm latest voyage planning and standing orders are available and briefed.",
              areaOfConcern: "Navigation",
              subAreaOfConcern: "Bridge Systems",
              typeOfFinding: "",
              severity: "",
              files: [
                {
                  id: "demo-file-nav-1",
                  url: "/reference-images/navigation-reference.svg",
                  caption: "Bridge documentation reference",
                  label: "Reference image",
                },
              ],
            },
            {
              id: "demo-nav-q2",
              code: "N2",
              prompt: "ECDIS, radar, gyro, and BNWAS remain fully operational without unresolved alarms.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 3,
              finding: true,
              comments: "BNWAS reset timing requires calibration check during the next maintenance window.",
              guidanceNotes: "Log any bridge system alarm, degraded sensor, or calibration concern.",
              areaOfConcern: "Navigation",
              subAreaOfConcern: "Bridge Systems",
              typeOfFinding: "Observation",
              severity: "MEDIUM",
              files: [
                {
                  id: "demo-file-nav-2",
                  url: "/reference-images/navigation-reference.svg",
                  caption: "Bridge system note",
                  label: "Finding image",
                },
              ],
            },
            {
              id: "demo-nav-q3",
              code: "N3",
              prompt: "Publications, checklists, and reporting routines were maintained during the inspection window.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "Publication control and bridge reporting discipline were satisfactory.",
              guidanceNotes: "Confirm publications and bridge routines are aligned with latest office guidance.",
              areaOfConcern: "Navigation",
              subAreaOfConcern: "Bridge Systems",
              typeOfFinding: "",
              severity: "",
              files: [],
            },
          ],
        },
      ],
    },
    {
      id: "demo-section-machinery",
      title: "Machinery and Safety",
      comments: "Engine room controls, safety equipment, and QHSE follow-up were sampled.",
      summary: {
        answered: 6,
        tested: 0,
        inspected: 6,
        notSighted: 0,
        notApplicable: 0,
        totalFindings: 1,
        evidenceCount: 2,
        questionCount: 6,
      },
      condition: { score: 3.8, scoredResponses: 6 },
      rating: { band: "High", mandatoryQuestions: 4, mandatoryQuestionsWithFindings: 0 },
      subsections: [
        {
          id: "demo-subsection-machinery-1",
          title: "Engine Room",
          location: "Engine Room",
          checklistId: 3,
          areaId: 301,
          totalCount: 3,
          doneCount: 3,
          summary: {
            answered: 3,
            tested: 0,
            inspected: 3,
            notSighted: 0,
            notApplicable: 0,
            totalFindings: 1,
            evidenceCount: 1,
            questionCount: 3,
          },
          condition: { score: 3.7, scoredResponses: 3 },
          rating: { band: "High", mandatoryQuestions: 2, mandatoryQuestionsWithFindings: 0 },
          comments: "Main plant reliability and maintenance backlog were discussed with ship staff.",
          questions: [
            {
              id: "demo-eng-q1",
              code: "E1",
              prompt: "Critical machinery remained operational and housekeeping standards were maintained.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "Engine room presentation and machinery readiness were satisfactory.",
              guidanceNotes: "Confirm machinery reliability, watchkeeping, and housekeeping remain aligned.",
              areaOfConcern: "Machinery",
              subAreaOfConcern: "Engine Room",
              typeOfFinding: "",
              severity: "",
              files: [
                {
                  id: "demo-file-eng-1",
                  url: "/reference-images/engine-reference.svg",
                  caption: "Machinery reference",
                  label: "Reference image",
                },
              ],
            },
            {
              id: "demo-eng-q2",
              code: "E2",
              prompt: "Any leakage, abnormal vibration, or temporary maintenance control affecting machinery readiness?",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 3,
              finding: true,
              comments: "One purifier drain line was under temporary monitoring until scheduled renewal.",
              guidanceNotes: "Capture any short-term control, leakage trend, or vibration concern.",
              areaOfConcern: "Machinery",
              subAreaOfConcern: "Engine Room",
              typeOfFinding: "Observation",
              severity: "LOW",
              files: [],
            },
            {
              id: "demo-eng-q3",
              code: "E3",
              prompt: "Maintenance backlog review confirmed critical jobs were within control.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "Critical maintenance items were controlled and tracked.",
              guidanceNotes: "Verify critical backlog items and spares support remain in control.",
              areaOfConcern: "Machinery",
              subAreaOfConcern: "Engine Room",
              typeOfFinding: "",
              severity: "",
              files: [],
            },
          ],
        },
        {
          id: "demo-subsection-safety-1",
          title: "Safety and QHSE",
          location: "Accommodation / Muster Zones",
          checklistId: 4,
          areaId: 401,
          totalCount: 3,
          doneCount: 3,
          summary: {
            answered: 3,
            tested: 0,
            inspected: 3,
            notSighted: 0,
            notApplicable: 0,
            totalFindings: 0,
            evidenceCount: 1,
            questionCount: 3,
          },
          condition: { score: 4.0, scoredResponses: 3 },
          rating: { band: "High", mandatoryQuestions: 2, mandatoryQuestionsWithFindings: 0 },
          comments: "Life-saving equipment readiness and safety leadership were checked in the demo scope.",
          questions: [
            {
              id: "demo-safe-q1",
              code: "S1",
              prompt: "Firefighting, lifesaving, and embarkation areas were ready for use.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "Safety equipment presentation matched the planned inspection scope.",
              guidanceNotes: "Verify firefighting, lifesaving, and embarkation arrangements remain ready.",
              areaOfConcern: "Safety",
              subAreaOfConcern: "Safety and QHSE",
              typeOfFinding: "",
              severity: "",
              files: [
                {
                  id: "demo-file-safe-1",
                  url: "/reference-images/lifesaving-reference.svg",
                  caption: "Safety arrangement reference",
                  label: "Reference image",
                },
              ],
            },
            {
              id: "demo-safe-q2",
              code: "S2",
              prompt: "Toolbox talk, permit controls, and work-rest protection were discussed with crew.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "QHSE controls and reporting expectations were reinforced during the walkthrough.",
              guidanceNotes: "Confirm crew safety engagement and permit discipline remain effective.",
              areaOfConcern: "Safety",
              subAreaOfConcern: "Safety and QHSE",
              typeOfFinding: "",
              severity: "",
              files: [],
            },
            {
              id: "demo-safe-q3",
              code: "S3",
              prompt: "Inspection evidence, ship comments, and office follow-up ownership were captured in PMSLink.",
              surveyStatus: "I",
              tested: false,
              inspected: true,
              notSighted: false,
              notApplicable: false,
              score: 4,
              finding: false,
              comments: "Inspection record was complete enough for seeded office review and reporting flows.",
              guidanceNotes: "Ensure the inspection narrative, evidence, and follow-up ownership are recorded.",
              areaOfConcern: "Safety",
              subAreaOfConcern: "Safety and QHSE",
              typeOfFinding: "",
              severity: "",
              files: [],
            },
          ],
        },
      ],
    },
  ],
} as const;

export default demoLiveBlueprint;
